server:
  port: 8881
spring:
  application:
    name: zuul
security:
  user:
    name: root
    password: password
  oauth2:
    client:
      accessTokenUri: 192.168.56.1:9097/uua/oauth/token
      userAuthorizationUri: 192.168.56.1:9097/oauth/authorize
      clientAuthenticationScheme: form
    resource:
       userInfoUri: 192.168.56.1:9097/uaa/user
       preferTokenInfo: false
  sessions: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000



zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: user-service

    customer:
      path: /cake/**
      sensitiveHeaders:
      serviceId: customer-service



