server:
  port: 8881

security:
  user:
    name: root
    password: password
  sessions: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000



zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: user-service

    customer:
      path: /cake/**
      sensitiveHeaders:
      serviceId: customer-service



